import type { Metadata } from 'next'
import { Inter, Montserrat, Caveat, Merienda } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import SiyanwuName from './components/name'
import Navbar from './components/Navbar'

const mont = Montserrat({ subsets: ['latin'] })
const caveat = Caveat({ subsets: ['latin'] })
const merienda = Merienda({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={caveat.className}>
        <div className='flex flex-col min-w-screen'>
          {/* NAV BAR */}
          <Navbar />
          <div className={`${merienda.className} min-h-screen w-full pt-20 bg-gray-100`}>
            {children}
          </div>

        </div>
      </body>
    </html>
  )
}
