import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='bg-gray-200 h-screen m-2 flex flex-col items-center'>
          <div className='bg-gray-300 h-20 w-60'>
            this is root layout
          </div>

          <div className='bg-gray-400 h-32 w-40'>
           {children}
          </div>

        </div>
      </body>
    </html>
  )
}
